services:
  - type: web
    name: fhir-rag-demo
    env: python
    plan: free
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    disks:
      - name: data
        mountPath: /opt/render/project/src
        sizeGB: 1
    envVars:
      - key: GEMINI_API_KEY
        sync: false   # you will enter it in dashboard